- hosts: ubuntu
  remote_user: "{{ a_user }}"
  ansible_ssh_pass: "{{ a_password }}"
  become: yes
  become_user: "{{ voltron }}"
  become_pass: "{{ voltron_pwd }}"
  tasks:
  - name: PLS UPDATE THIS BRO
    apt:
      update_cache: yes
      upgrade: 'yes'
    register: apt_update_status

  - name: DELETE OLD SHIT
    apt:
      autoremove: yes

  - name: REBOOT.me
    reboot:
      post_reboot_delay: 60
    when: apt_update_status.changed